### ISSUE TITLE
Team: steering committee 

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/bids-website#374]
@robertoostenveld  I invited new members but now we need to retire meritus (you and @guiomar) members from 
https://github.com/orgs/bids-standard/teams/steering/members

I guess then it should be some active member to be assigned as maintainer, so feel welcome to assign me.

**Comment by robertoostenveld** [comment]
I tried changing your role in the steering team to maintainer, but it somehow does not want to change it (or does not want to display your new role). I then tried changing all 5 steering group members to maintainer. However, it only shows Camille, Cyril and Dora as maintainers, not you and Ariel. Might that be because the two of you are also owners and therefore have all superpowers anyway?

I did just remove @guiomar and me from the team, so I think it is now as good as it gets.

**Comment by yarikoptic** [comment]
Great -- and now I found how to remove! ;) thank you @robertoostenveld
