### ISSUE TITLE
follow up improvements to the website

### ISSUE THREAD

**Issue by robertoostenveld** [bids-standard/bids-website#57]
If #56 gets merged, there is some technical follow up work to be done:

- [x] re-enable google analytics
- [x] consider whether PDF with previous versions of the specification should remain hosted on the website
- [ ] get a pdf version of the 2016 poster (the svg version is broken)
- [x] ensure that the `contributing guidelines` and `code of conduct` still work on github

**Comment by robertoostenveld** [comment]
Regarding keeping PDF versions of the specification on website, see https://github.com/bids-standard/bids-specification/issues/135 and https://groups.google.com/forum/#!topic/bids-discussion/z7c9mG9C6x8

**Comment by sappelhoff** [comment]
old and new PDFs are stored here: https://doi.org/10.5281/zenodo.3686061

--- 

the "Code of Conduct" works, because we have it in the `bids-standard/.github` repository, which tells GitHub to display it in any repo of the `bids-standard` organization (unless overridden locally).

See this screenshot, which is linking to out CoC (see for yourself by opening a new issue, then on the right lower side):

![grafik](https://user-images.githubusercontent.com/9084751/80687656-eb10e000-8aca-11ea-97eb-ea46f60a7dd8.png)

---

contributing guidelines are not shown. apparently there used to be some guidelines for the [old webpage](https://github.com/bids-standard/bids-website/blob/gh-pages/old_website/CONTRIBUTING.md) but they largely overlap with out [BIDS spec contrib guide](https://github.com/bids-standard/bids-specification/blob/master/CONTRIBUTING.md)

I think what is currently in the [README of this repo](https://github.com/bids-standard/bids-website#contributing-to-the-bids-website) suffices and we don't need a dedicated CONTRIBUTING.md.

---

> get a pdf version of the 2016 poster

I think that poster is very outdated, why do you want to have a fixed version? I consider that file to be in the "archive" of this repo (i.e., the "old_website" directory)

---

all in all, I think this issue can be closed, all jobs are done.

**Comment by Remi-Gau** [comment]
Will close this one. Not sure what's left to do here.
