### ISSUE TITLE
check that the website renders properly on small screens

### ISSUE THREAD

**Issue by robertoostenveld** [bids-standard/bids-website#63]
@emdupre mentioned this in https://github.com/bids-standard/bids-website/pull/56#issuecomment-567133376, which was followed up by @effigies and @adelavega 

I had a go at it and implemented a menu using bootstrap, which is now part of the deployed website. However, my html/css/js skills are not that great. Could you please check that it renders properly on your devices and/or in your browser?

If you have suggestions to improve the rendering of the header+menu, please suggest them as a PR.

**Comment by robertoostenveld** [comment]
Right now it has a "hamburger" style menu 😆. I used https://getbootstrap.com/docs/4.3/components/navbar/#nav and https://www.w3schools.com/bootstrap/bootstrap_navbar.asp to implement this. 

I personally also think that the menu is too wide, and the menu items (in BOLD, as before) take too much space. Feel free to propose a better organization of the menu and content of the pages, but please also keep in mind that we want to add **more** information to the website, so more menu items (or perhaps submenus) might be needed.

Some pieces of info that should be added:
- news (regular post, e.g. from the steering group, events, etc.
- governance document, and info on the steering group
- links to the starter-kit (to be moved from RTD to the main site)
- links to the BEPs (to be moved from RTD to the main site)
- possibly some of the content of the starter-kit wiki should be moved over (TBD)
- other content that currently lives in static/frozen google docs (i.e. not in development any more)

**Comment by adelavega** [comment]
I checked it out and I think it gets the job done, thanks!

It renders fine on my phone. My only nitpick is that when collapsed the menu is a grey bar, which is quite large, so it still dominates the space a bit. 

I think adding more menus is fine. My suggestion about removing some of them is mostly that I think some of this content does not deserve it's own page. I think by consolidating things such as "about" and "acknowledgements" we can clear up space for the new content, to keep the menu a reasonable size.

I do have this grey space to the right on the menu showing up on desktop though:
![Screenshot from 2019-12-19 17-02-14](https://user-images.githubusercontent.com/2774448/71216901-8ecac380-2281-11ea-9bbb-93d16e34920f.png)

I think this happens because my window is on an external monitor and thus is very wide. I don't see that empty space on my laptop monitor.

**Comment by robertoostenveld** [comment]
I believe the grey space on the right is due to the menu items being left-aligned. I hope someone else with better web skills can improve on this; I have already spent more time on the website conversion and do not want to become the de-facto website maintainer. Feel free to file a new issue regarding the menu display, keeping in mind that someone from the community (or you) will have to fix it.

**Comment by adelavega** [comment]
Yep, just documenting these. Fortunately these are fairly minor. I might give it a go if I have some time next decade ;)

**Comment by robertoostenveld** [comment]
I think the original issue has been sufficiently addressed, so let me close this issue. Feel free to reopen if needed.
